version: "3.9"

services:
  
  alticci_spa:
    build: ./frontend
    image: tnas/alticci-spa:1.0
    container_name: alticci-spa
    ports:
      - 8000:80
    depends_on:
      - alticci_api

  alticci_api:
    build: ./backend
    image: tnas/alticci-api:1.0
    container_name: alticci-api
    ports:
      - 8080:8080